# Generated by Django 3.2.7 on 2021-09-12 10:12

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_conversation_and_message_models"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("creator", django.db.models.expressions.F("invitee")), _negated=True
                ),
                name="check_creator_invitee_not_same",
            ),
        ),
    ]
